eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8090
spring:
  application:
    name: students
  datasource:
    url: jdbc:mysql://localhost:3306/students?useSSL=false
    username: webuser
    password: WebUser123*
  jpa:
    hibernate:
      ddl-auto: update

management:
  training:
    sampling:
      probability: 1.0